["Mob Drops"]
	#Wither drops insanium essence when killed with an Insanium weapon.
	wither_insanium = true
	#Ender Dragon drops insanium essence when killed with an Insanium weapon.
	dragon_insanium = true
